# Generated by Django 4.1.4 on 2023-07-10 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('discription', models.TextField(blank=True, max_length=500)),
                ('images', models.ImageField(upload_to='photos/offers')),
                ('starting_date', models.DateTimeField(auto_now_add=True)),
                ('ending_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
        ),
    ]
