# Generated by Django 4.1.4 on 2023-07-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_ending_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ending_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='starting_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
