# Generated by Django 4.1.4 on 2023-07-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_ending_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_shop_pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
