# Generated by Django 4.1.4 on 2023-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_offer_shop_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='starting_date',
            field=models.DateTimeField(null=True),
        ),
    ]
