# Generated by Django 4.1.4 on 2023-07-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_percent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_shop_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
