# Generated by Django 4.1.4 on 2023-07-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_alt_number_product_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_shop_name',
            field=models.CharField(max_length=100),
        ),
    ]
