# Generated by Django 4.1.4 on 2023-07-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_offer_shop_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
