# Generated by Django 4.1.4 on 2023-07-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Shop_Address',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='pin_code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
