# Generated by Django 4.1.4 on 2023-07-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_is_active_alter_account_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_shopowner',
            field=models.BooleanField(default=False),
        ),
    ]
